### ISSUE TITLE
Why everybody got a bonus?

### ISSUE THREAD

**Issue by hh3755** [SpankChain/sc_auction#1]
https://github.com/SpankChain/sc_auction/blob/d61b1f821e97757b56fb05feaad72c28fe7d3317/contracts/Auction.sol#L313

1. Not only for the one who join pre-sale and the one who did not will  both got the bonus?
2. Another question here is that if you did not have enough token left for bonus,The sale is fail too.

**Comment by ameensol** [comment]
1. Only presale buyers will receive a bonus. 
2. If we don't have enough token left for bonus, the following line would fail:

https://github.com/SpankChain/sc_auction/blob/d61b1f821e97757b56fb05feaad72c28fe7d3317/contracts/Auction.sol#L306
